name: ROS2 CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: eloquent
    - name: Run Test
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: |
          cpp_pubsub
          autonavi_msgs
        target-ros2-distro: eloquent
        
    - run: mkdir -p ros_ws/log
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with: 
        name: colcon-logs
        path: ros_ws/log
      if: always()
